# Generated by Django 3.2.6 on 2023-01-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanddata',
            name='years',
            field=models.CharField(default='', max_length=500),
        ),
    ]
